# Generated by Django 5.2.5 on 2025-10-30 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_funko_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='funko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.funko'),
        ),
    ]
